blueprint:
  name: Jasco Switch Double Taps
  description: >
    # Jasco Switch Double Taps
    
    **Version: 1.0**
    
    Create automations to react to double taps from supporting Jasco switches.

    The Jasco switches that support the use of double tap are currently not triggering events in ZWave-Js.  However using the "zwave_js.value_updated" trigger in home assistant it is still possible to offer double tap functionality on these switches.

          
    
    **Requirements:**
      - ZWave-JS
      - Jasco Z-Wave switches that support "Double Tap" functionality.  I personally have had luck using 14321 / ZW3005  with firmware 5.29.
      - "Group 3" of the switch must be set to include your controller device. You will probably need to use the community version of ZWave-JS in order to set group members.

    **Thanks:**  
      This blueprint is a reworking of the excellent GE Switch Double Taps blueprint by [kpine] (https://gist.github.com/kpine)

    
  domain: automation
  input:
    device:
      name: Switch Device
      description: A Jasco switch that supports double taps.
      selector:
        device:
          integration: zwave_js
          multiple: false
          manufacturer: Jasco          
    double_tap_on:
      name: Double Tap On
      description: Actions to run for a double tap on.
      default: []
      selector:
        action: {}
    double_tap_off:
      name: Double Tap Off
      description: Actions to run for a double tap off.
      default: []
      selector:
        action: {}
  source_url: https://github.com/cap60552/HA-Jasco-DoubleTap.git
mode: single
max_exceeded: silent
trigger:
  platform: zwave_js.value_updated
  device_id: !input device
  command_class: 32
  property: currentValue	
action:
- variables:
    value: '{{ trigger.current_value }}'
- choose:
  - conditions: '{{ value == 0 }}'
    sequence: !input double_tap_off
  - conditions: '{{ value == 255 }}'
    sequence: !input double_tap_on